name: GraphGeneration
channels:
  - defaults
dependencies:
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py38h2bbff1b_0
  - async-lru=2.0.4=py38haa95532_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.12.2=py38haa95532_0
  - brotli-python=1.0.9=py38hd77b12b_7
  - ca-certificates=2024.3.11=haa95532_0
  - colorama=0.4.6=py38haa95532_0
  - debugpy=1.6.7=py38hd77b12b_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - icu=73.1=h6c2663c_0
  - idna=3.4=py38haa95532_0
  - importlib_metadata=7.0.1=hd3eb1b0_0
  - importlib_resources=6.1.1=py38haa95532_1
  - ipython=8.12.2=py38haa95532_0
  - jpeg=9e=h2bbff1b_1
  - jsonschema-specifications=2023.7.1=py38haa95532_0
  - jupyter=1.0.0=py38haa95532_9
  - jupyter-lsp=2.2.0=py38haa95532_0
  - jupyter_client=8.6.0=py38haa95532_0
  - jupyter_console=6.6.3=py38haa95532_0
  - jupyter_core=5.5.0=py38haa95532_0
  - jupyter_events=0.8.0=py38haa95532_0
  - jupyter_server=2.10.0=py38haa95532_0
  - jupyter_server_terminals=0.4.4=py38haa95532_1
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.25.1=py38haa95532_0
  - jupyterlab_widgets=3.0.10=py38haa95532_0
  - krb5=1.20.1=h5b6d351_0
  - libclang13=14.0.6=default_h8e68704_1
  - libffi=3.4.4=hd77b12b_0
  - libpng=1.6.39=h8cc25b3_0
  - libpq=12.17=h906ac69_0
  - libsodium=1.0.18=h62dcd97_0
  - lz4-c=1.9.4=h2bbff1b_0
  - markupsafe=2.1.3=py38h2bbff1b_0
  - matplotlib-inline=0.1.6=py38haa95532_0
  - nbclient=0.8.0=py38haa95532_0
  - notebook=7.0.8=py38haa95532_0
  - notebook-shim=0.2.3=py38haa95532_0
  - openssl=3.0.13=h2bbff1b_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=23.2.1=py38haa95532_0
  - pkgutil-resolve-name=1.3.10=py38haa95532_1
  - platformdirs=3.10.0=py38haa95532_0
  - ply=3.11=py38_0
  - prometheus_client=0.14.1=py38haa95532_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.15.1=py38haa95532_1
  - pyqt=5.15.10=py38hd77b12b_0
  - pyqt5-sip=12.13.0=py38h2bbff1b_0
  - pysocks=1.7.1=py38haa95532_0
  - python=3.8.17=h1aa4202_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.16.2=py38haa95532_0
  - python-json-logger=2.0.7=py38haa95532_0
  - pyyaml=6.0.1=py38h2bbff1b_0
  - qt-main=5.15.2=h19c9488_10
  - qtconsole=5.5.1=py38haa95532_0
  - qtpy=2.4.1=py38haa95532_0
  - requests=2.31.0=py38haa95532_1
  - rfc3339-validator=0.1.4=py38haa95532_0
  - rfc3986-validator=0.1.1=py38haa95532_0
  - send2trash=1.8.2=py38haa95532_0
  - setuptools=68.0.0=py38haa95532_0
  - sip=6.7.12=py38hd77b12b_0
  - sniffio=1.3.0=py38haa95532_0
  - sqlite=3.41.2=h2bbff1b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - terminado=0.17.1=py38haa95532_0
  - tinycss2=1.2.1=py38haa95532_0
  - tomli=2.0.1=py38haa95532_0
  - typing_extensions=4.9.0=py38haa95532_1
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.38.4=py38haa95532_0
  - win_inet_pton=1.1.0=py38haa95532_0
  - winpty=0.4.3=4
  - xz=5.4.6=h8cc25b3_0
  - yaml=0.2.5=he774522_0
  - zeromq=4.3.5=hd77b12b_0
  - zlib=1.2.13=h8cc25b3_0
  - zstd=1.5.5=hd43e919_0
  - pip:
      - absl-py==2.0.0
      - accelerate==0.21.0
      - aiohttp==3.8.5
      - aiosignal==1.3.1
      - annotated-types==0.5.0
      - anyio==3.7.1
      - arrow==1.2.3
      - asttokens==2.2.1
      - async-timeout==4.0.2
      - attrs==23.2.0
      - babel==2.12.1
      - bleach==6.0.0
      - certifi==2023.7.22
      - cffi==1.15.1
      - chardet==5.2.0
      - charset-normalizer==3.2.0
      - click==8.1.6
      - cloudpickle==3.0.0
      - comm==0.1.3
      - contourpy==1.1.0
      - cycler==0.11.0
      - einops==0.6.1
      - einops-exts==0.0.4
      - ema-pytorch==0.2.3
      - exceptiongroup==1.1.2
      - executing==1.2.0
      - fastjsonschema==2.18.0
      - filelock==3.12.2
      - flatbuffers==1.12
      - fonttools==4.41.1
      - fqdn==1.5.1
      - frozenlist==1.4.0
      - fsspec==2023.6.0
      - future==0.18.3
      - gensim==4.3.2
      - google-auth-oauthlib==0.4.6
      - grpcio==1.34.1
      - h5py==3.1.0
      - huggingface-hub==0.16.4
      - hyperopt==0.2.7
      - imageio==2.33.1
      - importlib-metadata==6.8.0
      - importlib-resources==6.0.0
      - iprogress==0.4
      - ipykernel==6.25.0
      - ipywidgets==8.0.7
      - isoduration==20.11.0
      - jedi==0.19.0
      - jinja2==3.1.2
      - joblib==1.3.1
      - json5==0.9.14
      - jsonpointer==2.4
      - jsonschema==4.18.4
      - jupyter-client==8.3.0
      - jupyter-core==5.3.1
      - jupyter-events==0.6.3
      - jupyter-server==2.7.0
      - jupyterlab==4.0.3
      - jupyterlab-pygments==0.2.2
      - jupyterlab-server==2.24.0
      - jupyterlab-widgets==3.0.8
      - keras==2.8.0
      - keras-nightly==2.5.0.dev2021032900
      - keras-preprocessing==1.1.2
      - kiwisolver==1.4.4
      - kornia==0.6.12
      - lazy-loader==0.3
      - libclang==16.0.6
      - lightning-utilities==0.9.0
      - lmdb==1.4.1
      - matplotlib==3.7.2
      - mistune==3.0.1
      - mpmath==1.3.0
      - multidict==6.0.4
      - nbconvert==7.7.3
      - nbformat==5.9.1
      - nest-asyncio==1.5.7
      - networkx==3.1
      - numpy==1.24.4
      - oauthlib==3.2.2
      - opencv-python==4.8.0.74
      - outcome==1.3.0.post0
      - overrides==7.3.1
      - packaging==23.1
      - pandas==2.0.3
      - pillow==10.0.0
      - prometheus-client==0.17.1
      - prompt-toolkit==3.0.39
      - protobuf==5.26.1
      - psutil==5.9.5
      - py4j==0.10.9.7
      - pyaml==23.12.0
      - pyasn1==0.5.1
      - pyclipper==1.3.0.post5
      - pycryptodome==3.20.0
      - pydantic==2.1.1
      - pydantic-core==2.4.0
      - pymupdfb==1.24.1
      - pyparsing==3.0.9
      - pytorch-lightning==2.0.6
      - pytorch-warmup==0.1.1
      - pytz==2023.3
      - pywavelets==1.4.1
      - pywin32==306
      - pywinpty==2.0.11
      - pyzmq==25.1.0
      - rapidfuzz==3.8.1
      - rarfile==4.2
      - referencing==0.30.0
      - regex==2023.6.3
      - rpds-py==0.9.2
      - safetensors==0.3.1
      - scikit-image==0.21.0
      - scikit-learn==1.3.0
      - scikit-optimize==0.9.0
      - scipy==1.10.1
      - seaborn==0.12.2
      - selenium==4.19.0
      - sentencepiece==0.1.99
      - shapely==2.0.4
      - six==1.15.0
      - smart-open==6.4.0
      - sortedcontainers==2.4.0
      - soupsieve==2.4.1
      - stack-data==0.6.2
      - svgwrite==1.4.3
      - sympy==1.12
      - tensorboard==2.8.0
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.8.0
      - tensorflow-estimator==2.9.0
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==1.1.0
      - tf-estimator-nightly==2.8.0.dev2021122109
      - threadpoolctl==3.2.0
      - tifffile==2023.7.10
      - tokenizers==0.13.3
      - torch==2.0.1+cu118
      - torch-geometric==2.3.1
      - torchaudio==2.0.2+cu118
      - torchmetrics==1.0.1
      - torchvision==0.15.2
      - tornado==6.3.2
      - tqdm==4.65.0
      - traitlets==5.9.0
      - transformers==4.31.0
      - trio==0.25.0
      - trio-websocket==0.11.1
      - typing-extensions==4.10.0
      - tzdata==2023.3
      - uri-template==1.3.0
      - urllib3==1.26.18
      - wcwidth==0.2.6
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.6.1
      - werkzeug==3.0.1
      - widgetsnbextension==4.0.8
      - wrapt==1.12.1
      - wsproto==1.2.0
      - yarl==1.9.2
      - zipp==3.16.2
prefix: C:\Users\A\anaconda3\envs\GraphGeneration
